apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${ORG4_NS}
  name: create-pods
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${ORG4_NS}
  name: create-services
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pods
  namespace: ${ORG4_NS}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: deployer
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: create-pods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-services
  namespace: ${ORG4_NS}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: deployer
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: create-services # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""