#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org4-tls-cert-issuer
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: org4.example.com
  secretName: org4-tls-cert-issuer-secret
  issuerRef:
    name: root-tls-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org4-tls-cert-issuer
spec:
  ca:
    secretName: org4-tls-cert-issuer-secret


